// Import necessary packages, styles, and components
import info from "../styles/Info.module.css";
import React, { useState } from "react";
import util from "../styles/Util.module.css";
import EmailForm from "../components/EmailForm";

// Default component function
export default () => {
  // Create state for number and darkTheme using useState hook
  const [number, setNumber] = useState(() => 0);

  const style = {
    color: "#fbda61",
  };

  return (
    <>
      {/* Header and Explanation about useId */}
      <h1 className={util["header-1"]}>- useId -</h1>
      <h2 className={`${info["info"]} ${info["border-bottom"]}`}>
        <span>useId</span> is a React hook that generates a unique id for a
        component or HTML element. This hook is useful when you need to assign
        unique identifiers to elements, especially for accessibility purposes
        such as linking labels with form controls. When the component
        re-renders, the <span>useId</span> hook ensures the same unique id is
        returned, maintaining consistency across re-renders. This approach helps
        in avoiding the re-generation of ids, thereby maintaining the
        association between elements and improving overall accessibility and
        functionality.
      </h2>

      {/*  */}
      <EmailForm />
      <h2
        className={`${info["info"]} ${info["border-top"]} ${info["border-bottom"]}`}
      >
        By clicking on the <b style={style}>"Email"</b> text{" "}
        <b style={style}>below</b>, the corresponding input field{" "}
        <b style={style}> above </b> is activated. This interaction is made
        possible because both input fields share the same id, generated by the{" "}
        <span>useId</span> hook.
      </h2>
      <EmailForm />
    </>
  );
};
